[package]
name = "ray02"
version = "0.1.0"
authors = ["nekotako"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "renderer"
path = "src/lib.rs"

[dependencies]
image = "0.23.8"